import React from "react";

export const cosmeticsImages = {
    blockOne: [
        {
            url:'./images/2W9A9929.jpg'
        },
        {
            url:'./images/2W9A9947.jpg'
        },
        {
            url:'./images/NKWO1288.jpg'
        },
        {
            url:'./images/NKWO1307.jpg.tmp.jpeg'
        },
        {
            url:'./images/NKWO1338.jpg'
        },
        {
            url:'./images/NKWO1363.jpg'
        },
        {
            url:'./images/NKWO1904.jpg'
        },
        {
            url:'./images/NKWO1934.jpg'
        },
        {
            url:'./images/NKWO2041.jpg'
        },
    ],
    blockTwo: [
        {
            url:'./images/IMG_0141.jpg'
        },
        {
            url:'./images/IMG_3673.jpg'
        },
        {
            url:'./images/IMG_3794-2.jpg'
        },
        {
            url:'./images/IMG_4300-3.jpg'
        },
        {
            url:'./images/IMG_5393.jpg'
        },
        {
            url:'./images/IMG_7153.jpg'
        },
        {
            url:'./images/IMG_9167.jpg'
        },
    ],
    blockThree: [
        {
            url:'./images/IMG_2515.jpg'
        },
        {
            url:'./images/IMG_2475.jpg'
        },
        {
            url:'./images/NKWO1967.jpg'
        },
        {
            url:'./images/NKWO1984.jpg'
        },
        {
            url:'./images/NKWO1998.jpg'
        },
        {
            url:'./images/NKWO2080.jpg'
        },
        {
            url:'./images/NKWO2083.jpg'
        },
        {
            url:'./images/NKWO2090.jpg'
        },
        {
            url:'./images/NKWO2152.jpg'
        },
    ]
}