import React from "react";

export const creativeImages = {
    blockOne: [
        {
            url:'./images/IMG_0466.jpg'
        },
        {
            url:'./images/IMG_0515.jpg'
        },
        {
            url:'./images/IMG_0551.jpg'
        },
        {
            url:'./images/IMG_0603.jpg'
        },
        {
            url:'./images/mafa_195.jpg'
        },
        {
            url:'./images/mafa_177.jpg'
        },
        {
            url:'./images/mafa_166.jpg'
        },
    ],
    blockTwo: [
        {
            url:'./images/IMG_1307.jpg'
        },
        {
            url:'./images/IMG_1418.jpg'
        },
        {
            url:'./images/IMG_1455.jpg'
        },
        {
            url:'./images/IMG_1525.jpg'
        },
        {
            url:'./images/IMG_1589.jpg'
        },
        {
            url:'./images/2W9A0994.jpg'
        },
        {
            url:'./images/2W9A1304.jpg'
        },
        {
            url:'./images/2W9A1333.jpg'
        },
    ],
    blockThree: [
        {
            url:'./images/IMG_0203.jpg'
        },
        {
            url:'./images/IMG_0212.jpg'
        },
        {
            url:'./images/IMG_1838.jpg'
        },
        {
            url:'./images/IMG_1876.jpg'
        },
        {
            url:'./images/IMG_1908.jpg'
        },
        {
            url:'./images/IMG_1941.jpg'
        },
        {
            url:'./images/IMG_2920.jpg'
        },
    ]
}