import React from "react";

export const hairImages = {
    blockOne: [
        {
            url:'./images/IMG_0024.jpg'
        },
        {
            url:'./images/IMG_0125.jpg'
        },
        {
            url:'./images/IMG_0158.jpg'
        },
        {
            url:'./images/IMG_0438.jpg'
        },
        {
            url:'./images/IMG_0555.jpg'
        },
        {
            url:'./images/IMG_0677.jpg'
        },
        {
            url:'./images/IMG_0718.jpg'
        },
        {
            url:'./images/IMG_1051.jpg'
        },
        {
            url:'./images/IMG_1085.jpg'
        },
        {
            url:'./images/IMG_1181.jpg'
        },
        {
            url:'./images/IMG_1221.jpg'
        },
        {
            url:'./images/IMG_1326.jpg'
        },
        {
            url:'./images/IMG_1419.jpg'
        },
        {
            url:'./images/IMG_1441.jpg'
        },
        {
            url:'./images/IMG_1442.jpg'
        },
        {
            url:'./images/IMG_1545.jpg'
        },
        {
            url:'./images/IMG_1611.jpg'
        },
        {
            url:'./images/IMG_1638.jpg'
        },
        {
            url:'./images/IMG_1691.jpg'
        },
        {
            url:'./images/IMG_1825.jpg'
        },
        {
            url:'./images/IMG_1919.jpg'
        },
        {
            url:'./images/IMG_1976.jpg'
        },
        {
            url:'./images/IMG_2285.jpg'
        },
    ],
    blockTwo: [
        {
            url:'./images/IMG_2641.jpg'
        },
        {
            url:'./images/IMG_2810.jpg'
        },
        {
            url:'./images/IMG_3280.jpg'
        },
        {
            url:'./images/IMG_3454.jpg'
        },
        {
            url:'./images/IMG_3581.jpg'
        },
        {
            url:'./images/IMG_3649.jpg'
        },
        {
            url:'./images/IMG_3789.jpg'
        },
        {
            url:'./images/IMG_3947.jpg'
        },
        {
            url:'./images/IMG_4056.jpg'
        },
        {
            url:'./images/IMG_4124.jpg'
        },
        {
            url:'./images/IMG_4224.jpg'
        },
        {
            url:'./images/IMG_4304.jpg'
        },
        {
            url:'./images/IMG_4351.jpg'
        },
        {
            url:'./images/IMG_4474.jpg'
        },
        {
            url:'./images/IMG_4510.jpg'
        },
        {
            url:'./images/IMG_4563.jpg'
        },
        {
            url:'./images/IMG_4620.jpg'
        },
        {
            url:'./images/IMG_4649.jpg'
        },
        {
            url:'./images/IMG_4680.jpg'
        },
        {
            url:'./images/IMG_4743.jpg'
        },
        {
            url:'./images/IMG_4771.jpg'
        },
        {
            url:'./images/IMG_6037.jpg'
        },
        {
            url:'./images/IMG_6663.jpg'
        },
        
    ],
    blockThree: [
        {
            url:'./images/IMG_6796.jpg'
        },
        {
            url:'./images/IMG_7287.jpg'
        },
        {
            url:'./images/IMG_7442.jpg'
        },
        {
            url:'./images/IMG_7740.jpg'
        },
        {
            url:'./images/IMG_7828.jpg'
        },
        {
            url:'./images/IMG_7861.jpg'
        },
        {
            url:'./images/IMG_8019.jpg'
        },
        {
            url:'./images/IMG_8023.jpg'
        },
        {
            url:'./images/IMG_8224.jpg'
        },
        {
            url:'./images/IMG_8360.jpg'
        },
        {
            url:'./images/IMG_8424.jpg'
        },
        {
            url:'./images/IMG_8580.jpg'
        },
        {
            url:'./images/IMG_8713.jpg'
        },
        {
            url:'./images/IMG_8787.jpg'
        },
        {
            url:'./images/IMG_8909.jpg'
        },
        {
            url:'./images/IMG_9010.jpg'
        },
        {
            url:'./images/IMG_9028.jpg'
        },
        {
            url:'./images/IMG_9057.jpg'
        },
        {
            url:'./images/IMG_9374.jpg'
        },
        {
            url:'./images/IMG_9466.jpg'
        },
        {
            url:'./images/IMG_9952.jpg'
        },
        {
            url:'./images/IMG_372701.jpg'
        },
        {
            url:'./images/IMG_379101.jpg'
        },
    ]
}